spring:
  redis:
    host: localhost
    port: 6379
    database: 1
  datasource:
    url: jdbc:mysql://192.168.1.235:3306/merchant?autoReconnect=true&useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: abcd1234
  output:
    ansi:
      enabled: always